"""add_ontology_tables

Revision ID: 6ffc1500d43a
Revises: 9c7fe440b70b
Create Date: 2026-05-01 10:15:22.641983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffc1500d43a'
down_revision: Union[str, None] = '9c7fe440b70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontologies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='ontologystatus'), nullable=False),
    sa.Column('yaml_source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontologies_tenant_id'), 'ontologies', ['tenant_id'], unique=False)
    op.create_table('ontology_functions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ontology_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('handler', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.Text(), nullable=False),
    sa.Column('output_schema', sa.Text(), nullable=False),
    sa.Column('caching_ttl', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontology_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ontology_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('from_object', sa.String(), nullable=False),
    sa.Column('to_object', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('from_column', sa.String(), nullable=False),
    sa.Column('to_column', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontology_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ontology_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontology_properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('semantic_type', sa.String(), nullable=False),
    sa.Column('source_column', sa.String(), nullable=False),
    sa.Column('is_computed', sa.Boolean(), nullable=False),
    sa.Column('function_ref', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['ontology_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ontology_properties')
    op.drop_table('ontology_objects')
    op.drop_table('ontology_links')
    op.drop_table('ontology_functions')
    op.drop_index(op.f('ix_ontologies_tenant_id'), table_name='ontologies')
    op.drop_table('ontologies')
    # ### end Alembic commands ###
