"""add setup_stage to projects

Revision ID: 2cf16b1a0c59
Revises: 3fbb3344319d
Create Date: 2026-04-26 03:44:58.874366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf16b1a0c59'
down_revision = '3fbb3344319d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_goals_object_id'), ['object_id'], unique=False)

    with op.batch_alter_table('data_lineage', schema=None) as batch_op:
        batch_op.alter_column('transformation',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('dataset_assets', schema=None) as batch_op:
        batch_op.alter_column('selected_columns',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('filters',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('joins',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('domain_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_knowledge_object_id'), ['object_id'], unique=False)

    with op.batch_alter_table('health_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_rules_object_id'), ['object_id'], unique=False)

    with op.batch_alter_table('object_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_properties_object_id'), ['object_id'], unique=False)

    with op.batch_alter_table('project_api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_project_api_keys_project_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_stage', sa.String(length=20), server_default='idle', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('setup_stage')

    with op.batch_alter_table('project_api_keys', schema=None) as batch_op:
        batch_op.create_index('ix_project_api_keys_project_id', ['project_id'], unique=False)

    with op.batch_alter_table('object_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_properties_object_id'))

    with op.batch_alter_table('health_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_rules_object_id'))

    with op.batch_alter_table('domain_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_knowledge_object_id'))

    with op.batch_alter_table('dataset_assets', schema=None) as batch_op:
        batch_op.alter_column('joins',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('filters',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selected_columns',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('data_lineage', schema=None) as batch_op:
        batch_op.alter_column('transformation',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('business_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_goals_object_id'))

    # ### end Alembic commands ###
