"""phase1_foundation

Revision ID: 3fbb3344319d
Revises: 73db4391169e
Create Date: 2026-04-25 07:23:52.358450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbb3344319d'
down_revision = '73db4391169e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('ontology_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_entity', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('datasource_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_context', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('default_filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_object_name')
    )
    op.create_index(op.f('ix_ontology_objects_domain'), 'ontology_objects', ['domain'], unique=False)
    op.create_index(op.f('ix_ontology_objects_id'), 'ontology_objects', ['id'], unique=False)
    op.create_index(op.f('ix_ontology_objects_tenant_id'), 'ontology_objects', ['tenant_id'], unique=False)
    op.create_table('business_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_goals_id'), 'business_goals', ['id'], unique=False)
    op.create_table('domain_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_knowledge_id'), 'domain_knowledge', ['id'], unique=False)
    op.create_table('health_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('warning_threshold', sa.String(), nullable=True),
    sa.Column('critical_threshold', sa.String(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_rules_id'), 'health_rules', ['id'], unique=False)
    op.create_table('object_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('semantic_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_computed', sa.Boolean(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'name', name='uq_object_property_name')
    )
    op.create_index(op.f('ix_object_properties_id'), 'object_properties', ['id'], unique=False)
    op.create_table('ontology_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('from_object_id', sa.Integer(), nullable=False),
    sa.Column('to_object_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('from_field', sa.String(), nullable=False),
    sa.Column('to_field', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_object_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_object_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontology_relationships_id'), 'ontology_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_ontology_relationships_tenant_id'), 'ontology_relationships', ['tenant_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_synced', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_id'), 'pipeline_runs', ['pipeline_id'], unique=False)
    op.add_column('projects', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    with op.batch_alter_table('projects') as batch_op:
        batch_op.create_foreign_key('fk_projects_tenants', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_foreign_key('fk_users_tenants', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_users_invited_by', 'users', ['invited_by'], ['id'])
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_invited_by', type_='foreignkey')
        batch_op.drop_constraint('fk_users_tenants', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_constraint('fk_projects_tenants', type_='foreignkey')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_column('projects', 'tenant_id')

    op.drop_index(op.f('ix_pipeline_runs_pipeline_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_ontology_relationships_tenant_id'), table_name='ontology_relationships')
    op.drop_index(op.f('ix_ontology_relationships_id'), table_name='ontology_relationships')
    op.drop_table('ontology_relationships')
    op.drop_index(op.f('ix_object_properties_id'), table_name='object_properties')
    op.drop_table('object_properties')
    op.drop_index(op.f('ix_health_rules_id'), table_name='health_rules')
    op.drop_table('health_rules')
    op.drop_index(op.f('ix_domain_knowledge_id'), table_name='domain_knowledge')
    op.drop_table('domain_knowledge')
    op.drop_index(op.f('ix_business_goals_id'), table_name='business_goals')
    op.drop_table('business_goals')
    op.drop_index(op.f('ix_ontology_objects_tenant_id'), table_name='ontology_objects')
    op.drop_index(op.f('ix_ontology_objects_id'), table_name='ontology_objects')
    op.drop_index(op.f('ix_ontology_objects_domain'), table_name='ontology_objects')
    op.drop_table('ontology_objects')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
