"""add public_api_keys table

Revision ID: 886c3459dc84
Revises: 436291b1ef26
Create Date: 2026-03-27 02:50:26.417429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886c3459dc84'
down_revision = '436291b1ef26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_api_keys_id'), 'public_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_public_api_keys_key_hash'), 'public_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_public_api_keys_user_id'), 'public_api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_api_keys_user_id'), table_name='public_api_keys')
    op.drop_index(op.f('ix_public_api_keys_key_hash'), table_name='public_api_keys')
    op.drop_index(op.f('ix_public_api_keys_id'), table_name='public_api_keys')
    op.drop_table('public_api_keys')
    # ### end Alembic commands ###
