"""add invited_by field to users

Revision ID: b8263ba5fa2d
Revises: 003
Create Date: 2026-03-27 02:39:06.307288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8263ba5fa2d'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_lineage', 'transformation',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('dataset_assets', 'selected_columns',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('dataset_assets', 'filters',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('dataset_assets', 'joins',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_project_api_keys_project_id', table_name='project_api_keys')
    op.add_column('users', sa.Column('invited_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_invited_by'), 'users', ['invited_by'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_invited_by'), table_name='users')
    op.drop_column('users', 'invited_by')
    op.create_index('ix_project_api_keys_project_id', 'project_api_keys', ['project_id'], unique=False)
    op.alter_column('dataset_assets', 'joins',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset_assets', 'filters',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset_assets', 'selected_columns',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('data_lineage', 'transformation',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
