"""add invited_by field to users

Revision ID: b8263ba5fa2d
Revises: 003
Create Date: 2026-03-27 02:39:06.307288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8263ba5fa2d'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_invited_by'), ['invited_by'], unique=False)
        batch_op.create_foreign_key('fk_users_invited_by', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_invited_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_invited_by'))
        batch_op.drop_column('invited_by')
    # ### end Alembic commands ###
