"""add cache data models for stocks, financial indicators, and public query logs

Revision ID: eae86371d799
Revises: 886c3459dc84
Create Date: 2026-03-27 02:53:33.324807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae86371d799'
down_revision = '886c3459dc84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_financial_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=8), nullable=False),
    sa.Column('roe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grossprofit_margin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('netprofit_margin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('debt_to_assets', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_end_date', 'cached_financial_indicators', ['end_date'], unique=False)
    op.create_index('idx_ts_code', 'cached_financial_indicators', ['ts_code'], unique=False)
    op.create_index(op.f('ix_cached_financial_indicators_end_date'), 'cached_financial_indicators', ['end_date'], unique=False)
    op.create_index(op.f('ix_cached_financial_indicators_id'), 'cached_financial_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_cached_financial_indicators_ts_code'), 'cached_financial_indicators', ['ts_code'], unique=False)
    op.create_table('cached_stocks',
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('list_date', sa.String(length=8), nullable=True),
    sa.Column('list_status', sa.String(length=1), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_index('idx_area', 'cached_stocks', ['area'], unique=False)
    op.create_index('idx_industry', 'cached_stocks', ['industry'], unique=False)
    op.create_index(op.f('ix_cached_stocks_area'), 'cached_stocks', ['area'], unique=False)
    op.create_index(op.f('ix_cached_stocks_industry'), 'cached_stocks', ['industry'], unique=False)
    op.create_table('public_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_query_logs_created_at'), 'public_query_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_public_query_logs_id'), 'public_query_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_query_logs_id'), table_name='public_query_logs')
    op.drop_index(op.f('ix_public_query_logs_created_at'), table_name='public_query_logs')
    op.drop_table('public_query_logs')
    op.drop_index(op.f('ix_cached_stocks_industry'), table_name='cached_stocks')
    op.drop_index(op.f('ix_cached_stocks_area'), table_name='cached_stocks')
    op.drop_index('idx_industry', table_name='cached_stocks')
    op.drop_index('idx_area', table_name='cached_stocks')
    op.drop_table('cached_stocks')
    op.drop_index(op.f('ix_cached_financial_indicators_ts_code'), table_name='cached_financial_indicators')
    op.drop_index(op.f('ix_cached_financial_indicators_id'), table_name='cached_financial_indicators')
    op.drop_index(op.f('ix_cached_financial_indicators_end_date'), table_name='cached_financial_indicators')
    op.drop_index('idx_ts_code', table_name='cached_financial_indicators')
    op.drop_index('idx_end_date', table_name='cached_financial_indicators')
    op.drop_table('cached_financial_indicators')
    # ### end Alembic commands ###
